apiVersion: v1
kind: Pod
metadata:
  name: pod-quota-1
  namespace: test-quota
spec:
  containers:
  - name: www
    image: nginx:1.14-alpine
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
