apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: www
  name: www
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31001
  selector:
    app: www
  type: NodePort
status:
  loadBalancer: {}
