apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: proxy-pod
  name: proxy
spec:
  containers:
  - image: nginx:1.16
    name: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx

  - image: instavote/vote
    name: vote
    ports:
    - containerPort: 80

  restartPolicy: Always

  volumes:
  - name: nginx-config
    configMap:
      name: nginxconfigmap
