apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-proxy
  name: vote-proxy
spec:
  ports:
  - name: 8080-8080
    port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: proxy-pod
  type: NodePort
status:
  loadBalancer: {}
