apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod-env
  labels:
    app: pod-env
spec:
  containers:
  - image: lucj/messages:1.0
    name: api
    env:
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongo
          key: mongo_url
    
