apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod-vol
  labels:
    app: pod-vol
spec:
  containers:
  - image: lucj/messages:1.0
    name: api
    volumeMounts:
    - name: mongo-secret
      mountPath: /run/secrets
      readOnly: true
  volumes:
  - name: mongo-secret
    secret:
      secretName: mongo
      items:
      - key: mongo_url
        path: MONGODB_URL
