apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: service-vol
spec:
  ports:
  - name: api-vol
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31001
  selector:
    app: pod-vol
  type: NodePort
status:
  loadBalancer: {}
