apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: service-env
spec:
  ports:
  - name: api-env
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: pod-env
  type: NodePort
status:
  loadBalancer: {}
