apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weave-service
  name: weave-service
  namespace: weave
spec:
  ports:
  - name: 4040-4040
    port: 4040
    protocol: TCP
    targetPort: 4040
    nodePort: 31000
  selector:
    name: weave-scope-app
  type: NodePort
status:
  loadBalancer: {}
